// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reservation.Infrastructure.Persistence;

#nullable disable

namespace Reservation.Infrastructure.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20260604095534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Reservation.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<TimeOnly>("ArrivalTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("arrival_time");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<int>("GuestsCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("guests_count");

                    b.Property<bool>("HasAllergyAlert")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_allergy_alert");

                    b.Property<bool>("IsCelebration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_celebration");

                    b.Property<bool>("LateCancel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("late_cancel");

                    b.Property<bool>("NeedsHighChair")
                        .HasColumnType("INTEGER")
                        .HasColumnName("needs_high_chair");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("service_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("special_requests");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid?>("TableId")
                        .HasColumnType("TEXT")
                        .HasColumnName("table_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("idx_bookings_customer");

                    b.HasIndex("BookingDate", "ServiceId")
                        .HasDatabaseName("idx_bookings_date_service");

                    b.HasIndex("TableId", "BookingDate")
                        .HasDatabaseName("idx_bookings_table_date");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("Reservation.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsBlacklisted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_blacklisted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<int>("LateCancelCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("late_cancel_count");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("no_show_count");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VipLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("vip_level");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_customers_email");

                    b.HasIndex("Phone")
                        .HasDatabaseName("idx_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Reservation.Domain.Entities.DiningService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_minutes");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<TimeOnly>("LastBookingTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_booking_time");

                    b.Property<int>("MaxCovers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_covers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("dining_services", (string)null);
                });

            modelBuilder.Entity("Reservation.Domain.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCombinable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_combinable");

                    b.Property<int>("MinCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_capacity");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("zone");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("idx_tables_number");

                    b.ToTable("tables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
